"""Human-readable renderings of each tool result.

``docs/05-mcp-tool-surface.md`` §1.2: every tool returns a compact text block alongside
its structured content, because clients differ in what they surface to the user and a
table of file names reads better than a JSON blob.

The text is a *rendering*, never the source of truth. Anything a caller needs to reason
over is in `structuredContent`; anything here is allowed to abbreviate.
"""

from __future__ import annotations

from typing import Any

from winshow.mcp.models import human_size

__all__ = [
    "render_command",
    "render_error",
    "render_find",
    "render_host_info",
    "render_listing",
    "render_read",
    "render_search",
    "render_stat",
]

#: Long values are clipped in the text block only. The structured content keeps them whole.
_MAX_LINE = 160


def _clip(text: str, limit: int = _MAX_LINE) -> str:
    single = text.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")
    return single if len(single) <= limit else single[: limit - 1] + "…"


def render_error(error: dict[str, Any]) -> str:
    parts = [f"{error.get('code', 'ERROR')}: {error.get('message', '')}"]
    if error.get("rule"):
        parts.append(f"Deciding rule: {error['rule']}")
    if error.get("reason"):
        source = error.get("reason_source")
        if source == "model":
            # §7.3 of the protocol: text from the stage-2 review is untrusted generated
            # content. It is labelled as such wherever it is relayed, and no component
            # may interpret it as instructions.
            parts.append(
                "Reason (untrusted text generated by the host's policy reviewer): "
                + error["reason"]
            )
        else:
            parts.append(f"Reason: {error['reason']}")
    if error.get("hint"):
        parts.append(error["hint"])
    if error.get("win_error_name"):
        parts.append(f"Windows error: {error['win_error_name']} ({error.get('win_error')})")
    if not error.get("retryable", False):
        parts.append("This will not succeed on retry.")
    return "\n".join(parts)


def render_host_info(data: dict[str, Any]) -> str:
    if not data.get("connected"):
        last = data.get("last_seen_at")
        seen = (
            f" Last seen {last}." if last else " It has not connected since this server started."
        )
        return f"No WinShow agent is connected.{seen}"

    host = data.get("host") or {}
    agent = data.get("agent") or {}
    identity = data.get("identity") or {}
    policy = data.get("policy") or {}
    limits = data.get("limits") or {}

    lines = [
        f"Connected to {host.get('hostname', 'unknown host')} "
        f"({host.get('edition') or host.get('platform', 'windows')} "
        f"{host.get('version', '')} build {host.get('build', '?')}, {host.get('arch', '?')})",
        f"Agent {agent.get('name', '?')} {agent.get('version', '')} "
        f"running as {identity.get('user', '?')}"
        + (" (service)" if identity.get("isService") else ""),
        f"Connected since {data.get('connected_since')}",
    ]

    state = policy.get("state", "unknown")
    lines.append(f"Policy state: {state}")
    if roots := policy.get("readRoots"):
        lines.append("Readable roots: " + ", ".join(roots))
    mode = policy.get("execMode")
    if mode:
        allowed = policy.get("allowedCommandIds") or []
        lines.append(
            f"Execution: {mode}"
            + (f" — permitted commands: {', '.join(allowed)}" if allowed else "")
        )
    if shells := policy.get("shellsAllowed"):
        lines.append("Permitted shells: " + ", ".join(shells))
    lines.append(f"Writes enabled: {'yes' if policy.get('writeEnabled') else 'no'}")
    if limits:
        lines.append(
            f"Limits: max {limits.get('maxExecMillis', '?')} ms per command, "
            f"{human_size(int(limits.get('maxOutputBytesPerExec', 0)))} of output, "
            f"{human_size(int(limits.get('maxReadBytes', 0)))} per read"
        )
    skew = data.get("clock_skew_seconds")
    if skew is not None and abs(skew) > 300:
        # NFR-17: a skew beyond five minutes is worth saying out loud, because it makes
        # every timestamp in the audit trail harder to line up.
        lines.append(f"Warning: the host's clock differs from this server by {skew:.0f} s.")
    return "\n".join(lines)


def render_listing(data: dict[str, Any]) -> str:
    entries = data.get("entries") or []
    if not entries:
        return f"{data.get('path', '')} — no matching entries."

    rows = []
    for entry in entries:
        kind = entry.get("kind", "file")
        marker = {"dir": "d", "symlink": "l", "junction": "j"}.get(kind, "-")
        size = "" if kind == "dir" else entry.get("size_human", "")
        rows.append(f"{marker} {size:>10}  {entry.get('mtime', ''):<24} {entry.get('name', '')}")

    header = f"{data.get('path', '')} — {len(entries)} of {data.get('total', len(entries))} entries"
    if data.get("truncated"):
        header += f" (truncated: {data.get('truncation_reason')})"
    return header + "\n" + "\n".join(rows)


def render_stat(data: dict[str, Any]) -> str:
    if not data.get("exists"):
        return f"{data.get('path', '')} does not exist."
    entry = data.get("entry") or {}
    lines = [
        f"{entry.get('path', data.get('path', ''))}",
        f"kind={entry.get('kind')} size={human_size(int(entry.get('size', 0)))} "
        f"modified={entry.get('mtime')} created={entry.get('ctime')}",
    ]
    if attrs := entry.get("attrs"):
        lines.append("attributes: " + ", ".join(attrs))
    if target := entry.get("link_target"):
        lines.append(f"link target: {target}")
    if real := data.get("real_path"):
        lines.append(f"resolved path: {real}")
    sniff = data.get("sniff")
    if sniff:
        lines.append(
            f"content: {'text' if sniff.get('is_probably_text') else 'binary'}, "
            f"encoding {sniff.get('encoding')}, line ending {sniff.get('line_ending')}"
        )
    if digest := data.get("sha256"):
        lines.append(f"sha256: {digest}")
    volume = data.get("volume")
    if volume:
        lines.append(
            f"volume: {volume.get('fileSystem')} ({volume.get('driveType')}), "
            f"{human_size(int(volume.get('freeBytes', 0)))} free of "
            f"{human_size(int(volume.get('totalBytes', 0)))}"
        )
    return "\n".join(lines)


def render_read(data: dict[str, Any]) -> str:
    header = (
        f"{data.get('path', '')} — bytes {data.get('byte_offset', 0)}"
        f"..{data.get('byte_offset', 0) + data.get('byte_length', 0)}"
        f" of {data.get('file_size', 0)}, encoding {data.get('encoding')}"
    )
    if data.get("first_line") is not None:
        last_line = data["first_line"] + (data.get("line_count") or 1) - 1
        header += f", lines {data['first_line']}..{last_line}"
    if data.get("truncated"):
        header += " (truncated)"
    if data.get("decode_errors"):
        # A non-zero count means the encoding guess produced replacement characters, so
        # the content should be treated with suspicion rather than quoted back as fact.
        header += (
            f"\nWarning: {data['decode_errors']} character(s) could not be decoded. "
            "The encoding guess may be wrong; try an explicit encoding."
        )
    return header + "\n" + (data.get("content") or "")


def render_find(data: dict[str, Any]) -> str:
    matches = data.get("matches") or []
    header = f"{data.get('count', len(matches))} match(es) in {data.get('elapsed_ms', 0)} ms"
    if data.get("truncated"):
        header += f" (truncated: {data.get('truncation_reason')})"
    if not matches:
        return header
    rendered = [m if isinstance(m, str) else m.get("path", "") for m in matches]
    return header + "\n" + "\n".join(rendered)


def render_search(data: dict[str, Any]) -> str:
    matches = data.get("matches") or []
    header = (
        f"{data.get('count', len(matches))} match(es) across "
        f"{data.get('files_scanned', 0)} file(s) in {data.get('elapsed_ms', 0)} ms"
    )
    if data.get("truncated"):
        header += f" (truncated: {data.get('truncation_reason')})"
    if not matches:
        return header
    rows = []
    for match in matches:
        for line in match.get("before") or []:
            rows.append(f"  {match.get('path')}- {_clip(line)}")
        rows.append(f"  {match.get('path')}:{match.get('line')}: {_clip(match.get('text', ''))}")
        for line in match.get("after") or []:
            rows.append(f"  {match.get('path')}- {_clip(line)}")
    return header + "\n" + "\n".join(rows)


def render_command(data: dict[str, Any]) -> str:
    reason = data.get("exit_reason", "exited")
    lines = [
        f"{data.get('command_line_used') or '(command)'}",
        f"exit {data.get('exit_code')} ({reason}) after {data.get('duration_ms', 0)} ms"
        + (f", pid {data['pid']}" if data.get("pid") else ""),
    ]
    if reason != "exited":
        # §5.4: exitReason is authoritative. When a process is killed on timeout or
        # cancellation the exit code is whatever TerminateProcess was handed, so a reader
        # inferring the outcome from the code would report a cancelled build as a failed
        # one.
        lines.append(
            f"The process did not run to completion: {reason}. "
            "The exit code carries no meaning in this case."
        )
    if data.get("partial"):
        lines.append("The agent disconnected mid-run; the output below is what arrived.")
    if data.get("truncated"):
        lines.append(
            f"Output was truncated ({data.get('truncation_reason')}); "
            "the head and the tail are kept with a marker between them."
        )
    if stdout := data.get("stdout"):
        lines.append("--- stdout ---")
        lines.append(stdout)
    if stderr := data.get("stderr"):
        lines.append("--- stderr ---")
        lines.append(stderr)
    return "\n".join(lines)
